# Generated by Django 5.0 on 2023-12-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='artists'),
        ),
    ]
