# Generated by Django 5.0 on 2023-12-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracks', '0003_video_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='file_128',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='album',
            name='file_320',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
