# Generated by Django 5.0 on 2023-12-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracks', '0004_album_file_128_album_file_320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('-created',), 'verbose_name': 'آلبوم', 'verbose_name_plural': 'آلبوم ها'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'هنرمند', 'verbose_name_plural': 'هنرمندان'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'سبک', 'verbose_name_plural': 'سبک ها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'دیدگاه', 'verbose_name_plural': 'دیدگاه ها'},
        ),
        migrations.AlterModelOptions(
            name='podcast',
            options={'ordering': ('-created',), 'verbose_name': 'پادکست', 'verbose_name_plural': 'پادکست ها'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('-created',), 'verbose_name': 'موزیک', 'verbose_name_plural': 'موزیک ها'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'موزیک ویدیو', 'verbose_name_plural': 'موزیک ویدیو ها'},
        ),
    ]
