# Generated by Django 5.0 on 2023-12-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracks', '0005_alter_album_options_alter_artist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='single',
            field=models.BooleanField(default=True, verbose_name='سینگل ترک'),
        ),
    ]
